### ISSUE TITLE
Language server crashes repeatedly when using presets

### ISSUE THREAD

**Issue by Siuhnexus** [sjsone/vscode-neos-fusion-lsp#13]
I tried to setup good color defaults (colors shipped by Tailwind) to choose from using a [color picker](https://github.com/Sebobo/Shel.Neos.ColorPicker). This is a shortened version of my Settings.yaml:
```yaml
Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          "color":
            "preloaded":
              type: string
              defaultValue: gray
              ui:
                reloadIfChanged: true
                inspector:
                  editor: "Shel.Neos.ColorPicker/ColorPickerEditor"
                  editorOptions:
                    mode: "preset"
                    presetColors: [{
                      color: "#fb2c36",
                      value: "red"
                    }, {
                      color: "#ff6900",
                      value: "orange"
                    }, {
                      color: "#fe9a00",
                      value: "amber"
                    }]
                    allowEmpty: false
```
And this is my node definition:
```yaml
'Redacted.Site:Document.Homepage':
  superTypes:
    'Neos.Neos:Site': true
  ui:
    icon: globe
    label: 'Redacted'
    inspector:
      tabs:
        'theming':
          label: 'Seitendesign'
          position: 900
          icon: 'brush'
      groups:
        'logo':
          label: 'Logo'
          position: 0
          icon: 'picture'
          tab: 'theming'
        'colors':
          label: 'Farben'
          position: 100
          icon: "tint"
          tab: "theming"
  properties:
    "primary":
      options:
        preset: "color.preloaded"
      ui:
        label: "Primärfarbe"
        inspector:
          group: "colors"
    "secondary":
      options:
        preset: "color.preloaded"
      ui:
        label: "Sekundärfarbe"
        inspector:
          group: "colors"
```
This works perfectly in the NEOS backend, which is why I don't think I made a mistake. It also works when not using a preset (so there's no issue with yaml parsing or something like that).

**Comment by Siuhnexus** [comment]
And is this repo meant for unix development only? The project:clone-server command would indicate that. I'd like to learn from this or even help solve my own problem.

**Comment by sjsone** [comment]
HI @Siuhnexus 
thank you very much for bringing this issue to awareness. 

### The issue

Unfortunately I cannot reproduce the issue on the `pre-release` version: 

**formatted `Settings.yaml`**
```yaml
Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          "color":
            "preloaded":
              type: string
              defaultValue: gray
              ui:
                reloadIfChanged: true
                inspector:
                  editor: "Shel.Neos.ColorPicker/ColorPickerEditor"
                  editorOptions:
                    mode: "preset"
                    presetColors:
                      [
                        { color: "#fb2c36", value: "red" },
                        { color: "#ff6900", value: "orange" },
                        { color: "#fe9a00", value: "amber" },
                      ]
                    allowEmpty: false

```

**RootPage.yaml**:
```yaml
"SJS.Site:Document.RootPage":
  superTypes:
    "Neos.Neos:Document": true
  ui:
    icon: file
    label: "SJS.Site Root Page"
    inspector:
      tabs:
        "theming":
          label: "Seitendesign"
          position: 900
          icon: "brush"
      groups:
        "logo":
          label: "Logo"
          position: 0
          icon: "picture"
          tab: "theming"
        "colors":
          label: "Farben"
          position: 100
          icon: "tint"
          tab: "theming"
  childNodes:
    main:
      type: "Neos.Neos:ContentCollection"
  constraints:
    nodeTypes:
      SJS.Site:Document.RootPage: false

  properties:
    "primary":
      options:
        preset: "color.preloaded"
      ui:
        label: "Primärfarbe"
        inspector:
          group: "colors"
    "secondary":
      options:
        preset: "color.preloaded"
      ui:
        label: "Sekundärfarbe"
        inspector:
          group: "colors"
```

Even the Flow Configurationi Explorer reflects the configuration:
<img width="350" alt="Image" src="https://github.com/user-attachments/assets/76dc391d-542b-4cc1-ae1f-901e69775982" />

### Debugging
You can open the _Output_ view and select the `Neos Fusion LSP`:
<img width="946" alt="Image" src="https://github.com/user-attachments/assets/745c585b-2db5-44cc-a977-bd4e688532dc" />

Combined with the VS Code setting `"neosFusionLsp.logging.level": "verbose",` you should get a (somewhat) detailed error description why the server dies and restarts. 

**Also**: what version of the extension are you using and which OS are you running on?

### Development on Windows

By your question I am guessing you are running on Windows. There is nothing inherently against developing the extension on Windows although I have never tested it to be honest. 

The key element is just `esbuild`. The `project:clone-server` script is just a for convenience

**Comment by Siuhnexus** [comment]
Ok with the output tab (silly me for not using that before) I can now tell that this really is a formatting problem. With your way of JSON formatting it works. However, since YAML should be a superset of JSON, I wonder whether different ways of formatting JSON should be accepted as well. In NodeType-configs "incorrectly" formatted JSON works fine with the LSP. They are not parsed at all, since they don't affect Fusion in any way, right?

**Comment by sjsone** [comment]
### YAML 

This exact formatting should not be parsed as valid YAML to begin with:
```yaml
Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          "color":
            "preloaded":
              type: string
              defaultValue: gray
              ui:
                reloadIfChanged: true
                inspector:
                  editor: "Shel.Neos.ColorPicker/ColorPickerEditor"
                  editorOptions:
                    mode: "preset"
                    presetColors: [{
                      color: "#fb2c36",
                      value: "red"
                    }, {
                      color: "#ff6900",
                      value: "orange"
                    }, {
                      color: "#fe9a00",
                      value: "amber"
                    }]
                    allowEmpty: false
```

Correct would be 

```yaml
Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          "color":
            "preloaded":
              type: string
              defaultValue: gray
              ui:
                reloadIfChanged: true
                inspector:
                  editor: "Shel.Neos.ColorPicker/ColorPickerEditor"
                  editorOptions:
                    mode: "preset"
                    presetColors: [{
                        color: "#fb2c36",
                        value: "red"
                      }, {
                        color: "#ff6900",
                        value: "orange"
                      }, {
                        color: "#fe9a00",
                        value: "amber"
                      }]
                    allowEmpty: false
```

So everything in `presetColors` has to be indented. 


### Configurations and NodeTypes

The normal **release** version uses a simple built-in parser to parse the NodeTypes where as the Settings get parsed via the [`yaml` Package](https://www.npmjs.com/package/yaml).

The current **pre-release** version uses the built-in parser in conjunction with the [`yaml` Package](https://www.npmjs.com/package/yaml) to parse all `.yaml` files. This is done to completely built up the Flow Configuration for use in EEL-Helper determination and more.

I will probably pivot to only using the [`yaml` Package](https://www.npmjs.com/package/yaml) in the future
